### ISSUE TITLE
Configuração de Deploy na Configr

### ISSUE THREAD

**Issue by alvesisaque** [Dulce-Work-Schedule/2018.1-Dulce_User#43]
Nessa issue será realizado:
- Conversar com a @gabibguedes para verificar a possibilidade de fazer o Deploy no servidor dela.

Critérios de aceitação:
- Definir se utilizaremos esse servidor ou continuaremos com o da Amazon;
- Criar issues se for realizar a transferência.

**Comment by gag2502** [comment]
Recebi instruções da @gabibguedes e vou verificar a possibilidade de usar alguns hosts por esse caminho

**Comment by egewarth** [comment]
@gag2502 e @gabibguedes , podemos fechar essa issue?

**Comment by gag2502** [comment]
@egewarth Podemos
